begin;
create table if not exists wishlist_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,product_id uuid not null references products(id) on delete cascade,created_at timestamptz default now(),unique(user_id,product_id));
create table if not exists addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,label text default 'Home',full_name text,line1 text,line2 text,city text,state text,postal_code text,country text default 'US',phone text,is_default boolean default false,created_at timestamptz default now());
create table if not exists abandoned_carts(id uuid primary key default gen_random_uuid(),user_id uuid references profiles(id),email text,items jsonb default '[]',recovered_at timestamptz,last_reminder_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists email_events(id uuid primary key default gen_random_uuid(),user_id uuid references profiles(id),email text,event_type text,status text default 'queued',provider_id text,payload jsonb default '{}',created_at timestamptz default now());
create table if not exists affiliate_clicks(id bigserial primary key,referral_id uuid references referrals(id),code text,session_id text,path text,created_at timestamptz default now());
create table if not exists product_questions(id uuid primary key default gen_random_uuid(),product_id uuid references products(id) on delete cascade,user_id uuid references profiles(id),email text,question text not null,answer text,status text default 'pending',created_at timestamptz default now(),answered_at timestamptz);
create unique index if not exists orders_provider_order_id_key on orders(provider_order_id) where provider_order_id is not null;
create unique index if not exists wholesale_accounts_user_id_key on wholesale_accounts(user_id);
create unique index if not exists design_votes_design_visitor_key on design_votes(design_id,visitor_id) where visitor_id is not null;
alter table wishlist_items enable row level security;alter table addresses enable row level security;alter table notifications enable row level security;alter table loyalty_transactions enable row level security;alter table subscriptions enable row level security;alter table wholesale_accounts enable row level security;alter table affiliate_applications enable row level security;
drop policy if exists "own wishlist" on wishlist_items;create policy "own wishlist" on wishlist_items for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "own addresses" on addresses;create policy "own addresses" on addresses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "own notifications" on notifications;create policy "own notifications" on notifications for select using(auth.uid()=user_id);
drop policy if exists "own loyalty" on loyalty_transactions;create policy "own loyalty" on loyalty_transactions for select using(auth.uid()=user_id);
drop policy if exists "own subscriptions" on subscriptions;create policy "own subscriptions" on subscriptions for select using(auth.uid()=user_id);
drop policy if exists "own wholesale" on wholesale_accounts;create policy "own wholesale" on wholesale_accounts for select using(auth.uid()=user_id);
drop policy if exists "own affiliate applications" on affiliate_applications;create policy "own affiliate applications" on affiliate_applications for select using(auth.uid()=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,email,full_name,referral_code) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),upper(substr(md5(new.id::text),1,8))) on conflict(id) do nothing;return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.increment_design_vote() returns trigger language plpgsql security definer as $$begin update design_vault_items set vote_count=vote_count+1 where id=new.design_id;return new;end;$$;
drop trigger if exists design_vote_increment on design_votes;create trigger design_vote_increment after insert on design_votes for each row execute procedure public.increment_design_vote();
commit;
